server:
  port: 9001


#单机配置/测试无误
spring:
  redis:
    host: 192.168.159.20
    port: 6377
    lettuce:
      pool:
        max-wait: 100000
        max-idle: 10
        max-active: 100
    timeout: 5000

#集群配置
#spring:
#  redis:
#    database: 0
#    # 集群设置 begin
#    cluster:
#      nodes:
#        - 192.168.159.20:6377
#        - 192.168.159.20:6378
#        - 192.168.159.20:6379
#      max-redirects: 3 # 获取失败 最大重定向次数
#    #集群设置 end
#    #单节点 begin
#    #    host: 10.217.17.74
#    #    port: 7000
#    #单节点 end
#    lettuce:
#      pool:
#        max-wait: 100000
#        max-idle: 10
#        max-active: 100
#    timeout: 5000