server:
  port: 80

#作为eureka的客户端，但是不注册到eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7004.com:7004/eureka/,http://eureka7005.com:7005/eureka/
    register-with-eureka: false

#  暂时不需要
#    fetch-registry: true
#ribbon:
#  eureka:
#    enable: true
#
#spring:
#  application:
#    name: server-ribbon